name: memo_keitai
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  openapi_generator_annotations: ^6.1.0
  memoapi:
    path: ./memoapi
  http: ^1.4.0
  markdown_widget: ^2.3.2+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  openapi_generator: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png